// 请求状态选项
export const STATUS_OPTIONS = [
  { label: "未解决", value: 0 },
  { label: "已解决", value: 1 },
  { label: "关闭", value: 2 },
];

// 资源请求接口
export interface ResourceRequest {
  id: number;
  title: string;
  content: string;
  user_id: number;
  user_name: string;
  college_id: number;
  college_name: string;
  major_id: number;
  major_name: string;
  category_id: number;
  category_name: string;
  reply_count: number;
  view_count: number;
  status: number; // 0-未解决，1-已解决，2-关闭
  create_time: string;
  update_time: string;
  is_deleted: number;
}

// 模拟资源请求数据
export const MOCK_RESOURCE_REQUEST_DATA: ResourceRequest[] = [
  {
    id: 1,
    title: "求高等数学(第七版)期末复习资料",
    content: "请问有人有高数期末复习资料吗？最好是第七版的同步练习题和答案，谢谢！",
    user_id: 101,
    user_name: "张三",
    college_id: 1745,
    college_name: "数学学院",
    major_id: 5423,
    major_name: "数学与应用数学",
    category_id: 1,
    category_name: "学习笔记",
    reply_count: 3,
    view_count: 45,
    status: 1,
    create_time: "2025-04-20 09:15:38",
    update_time: "2025-04-20 17:23:41",
    is_deleted: 0,
  },
  {
    id: 2,
    title: "求ACCA考试案例分析资料",
    content: "有没有人有ACCA F1-F9的案例分析资料？特别是F7和F8的内容，非常感谢！",
    user_id: 102,
    user_name: "李四",
    college_id: 1738,
    college_name: "社会审计学院",
    major_id: 5406,
    major_name: "审计学",
    category_id: 3,
    category_name: "资料文件",
    reply_count: 2,
    view_count: 32,
    status: 0,
    create_time: "2025-04-18 14:25:36",
    update_time: "2025-04-21 10:31:56",
    is_deleted: 0,
  },
  {
    id: 3,
    title: "计算机网络实验操作指导",
    content: "求一份计算机网络实验的详细操作指导，最好包含抓包分析和路由配置的内容。",
    user_id: 103,
    user_name: "王五",
    college_id: 1744,
    college_name: "计算机学院",
    major_id: 5419,
    major_name: "计算机科学与技术",
    category_id: 6,
    category_name: "实验报告",
    reply_count: 1,
    view_count: 28,
    status: 1,
    create_time: "2025-04-17 10:32:24",
    update_time: "2025-04-22 14:28:37",
    is_deleted: 0,
  },
  {
    id: 4,
    title: "法学考研真题及解析",
    content: "求近五年法学考研真题及详细解析，特别是法理学和民法学部分，谢谢！",
    user_id: 104,
    user_name: "赵六",
    college_id: 1729,
    college_name: "法学院",
    major_id: 5369,
    major_name: "法学",
    category_id: 3,
    category_name: "资料文件",
    reply_count: 1,
    view_count: 37,
    status: 0,
    create_time: "2025-04-16 15:45:21",
    update_time: "2025-04-23 16:52:14",
    is_deleted: 0,
  },
  {
    id: 5,
    title: "化学实验危险品处理规范",
    content: "请问有没有最新版的化学实验室危险品处理规范文档？需要做实验安全培训。",
    user_id: 105,
    user_name: "钱七",
    college_id: 1732,
    college_name: "化学学院",
    major_id: 5384,
    major_name: "应用化学",
    category_id: 6,
    category_name: "实验报告",
    reply_count: 1,
    view_count: 23,
    status: 1,
    create_time: "2025-04-15 08:52:33",
    update_time: "2025-04-24 11:34:27",
    is_deleted: 0,
  },
  {
    id: 6,
    title: "金融学原理PPT课件",
    content: "求一份金融学原理的最新PPT课件，最好是中英双语的版本，谢谢！",
    user_id: 106,
    user_name: "孙八",
    college_id: 1733,
    college_name: "金融学院",
    major_id: 5388,
    major_name: "金融学",
    category_id: 2,
    category_name: "课件PPT",
    reply_count: 2,
    view_count: 30,
    status: 1,
    create_time: "2025-04-14 11:23:45",
    update_time: "2025-04-25 14:23:17",
    is_deleted: 0,
  },
  {
    id: 7,
    title: "统计学习方法习题答案",
    content: "谁有《统计学习方法》这本书的习题答案？需要自学这门课程，希望有详细解答。",
    user_id: 107,
    user_name: "周九",
    college_id: 1745,
    college_name: "数学学院",
    major_id: 5424,
    major_name: "统计学",
    category_id: 4,
    category_name: "电子书籍",
    reply_count: 0,
    view_count: 18,
    status: 0,
    create_time: "2025-04-13 16:35:27",
    update_time: "2025-04-13 16:35:27",
    is_deleted: 0,
  },
  {
    id: 8,
    title: "英语专业八级备考资料",
    content: "求英语专业八级的备考资料，包括听力、阅读、写作和翻译部分，越详细越好！",
    user_id: 108,
    user_name: "吴十",
    college_id: 1730,
    college_name: "外国语学院",
    major_id: 5373,
    major_name: "英语",
    category_id: 3,
    category_name: "资料文件",
    reply_count: 0,
    view_count: 22,
    status: 0,
    create_time: "2025-04-12 09:24:15",
    update_time: "2025-04-12 09:24:15",
    is_deleted: 0,
  },
  {
    id: 9,
    title: "机器学习与深度学习实践教程",
    content: "有没有关于机器学习和深度学习的实践教程？最好是包含代码和案例分析的那种。",
    user_id: 109,
    user_name: "郑十一",
    college_id: 1744,
    college_name: "计算机学院",
    major_id: 5419,
    major_name: "计算机科学与技术",
    category_id: 4,
    category_name: "电子书籍",
    reply_count: 0,
    view_count: 15,
    status: 0,
    create_time: "2025-04-11 14:52:36",
    update_time: "2025-04-11 14:52:36",
    is_deleted: 0,
  },
  {
    id: 10,
    title: "会计学原理期末复习资料[已删除]",
    content: "求会计学原理的期末复习资料，包括考点梳理和习题，谢谢！",
    user_id: 110,
    user_name: "王十二",
    college_id: 1739,
    college_name: "会计学院",
    major_id: 5407,
    major_name: "会计学",
    category_id: 1,
    category_name: "学习笔记",
    reply_count: 0,
    view_count: 8,
    status: 2,
    create_time: "2025-04-10 10:15:23",
    update_time: "2025-04-10 15:32:41",
    is_deleted: 1,
  },
];
