global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080', 'registry:8088', 'config:8888']

  - job_name: 'nacos'
    metrics_path: '/nacos/actuator/health'
    static_configs:
      - targets: ['nacos-standalone:8848']

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
        labels:
          application: "mysql"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          application: "redis"

  - job_name: "elasticsearch"
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets: ["elasticsearch:9200"]
        labels:
          application: "elasticsearch"

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]
        labels:
          application: "rabbitmq" 