global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8088', 'host.docker.internal:8888']

  # 选项1:
  - job_name: 'nacos'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8848']

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
        labels:
          application: "mysql"

  - job_name: "redis"
    static_configs:
      - targets: ["host.docker.internal:9121"]
        labels:
          application: "redis"

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["host.docker.internal:9114"]
        labels:
          application: "elasticsearch"

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["host.docker.internal:9419"]
        labels:
          application: "rabbitmq" 