server:
  port: 8888

spring:
  application:
    name: audit-study-hub-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/config
    nacos:
      discovery:
        enabled: false
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: false
    enable:
      jvm: false
      process: false
      system: false
